#!/bin/sh

./script_compil.sh
#./original.sh
#./deroulage.sh
#./deroulage_2.sh
#./deroulage_3.sh
#./ordre.sh
#./ordre_2.sh
#./ordre_3.sh
#./tilling.sh
#./mkl.sh
#./parallel_1.sh
#./original_avx.sh
#./parallel_1_avx.sh
#./tilling_2.sh
#./affinity.sh
./parallel_2.sh
./parallel_2_avx.sh
./parallel_2_avx_vec.sh
